### ISSUE TITLE
Error resolving URL

### ISSUE THREAD

**Issue by ckoryom** [chibby0ne/download_series#1]
urllib2.urlopen(real_url)

Method:

real_url = create_url(SERIES, series_name)

Failing to resolve URL -> http://watch-series-tv.to/serie/   ---> URL doesnt exist anymore:

Should be replaced with: http://watch-series-tv.to/series/

**Comment by chibby0ne** [comment]
Fixed with new commit! That prefix URL was not the problem (e.g: http://watch-series-tv.to/serie/game_of_thrones). The problem was that watchseries decided to encode the links of each episode to the video hosters (i.e: gorillavid.in) and scraping the website didn't reveal any string containing "gorillavid" which is how it was done before. 
![ss](https://cloud.githubusercontent.com/assets/4380812/9316540/f07a86f2-4535-11e5-9540-c2024acb10bd.png)

![ss_source](https://cloud.githubusercontent.com/assets/4380812/9316625/72c4f7fa-4536-11e5-9f02-0848f788e904.png)

So now we don't even scrape this website because from the url we can decode using base64 the url to gorillavid and continue doing the same thing as before
